### PR TITLE
Fix for shelving order in typeclasses eauto.

### PR DESCRIPTION
**Pull request by Zimmi48**
Before this fix, unshelve typeclasses eauto would produce sub-goals
in the reverse order compared to when they were first shelved.

### CODE REVIEW

**Comment by mattam82** [comment]
@Zimmi48  I just rebased the hintsforward branch, I think that's the one it should be based on, no?

**Comment by Zimmi48** [comment]
Alright, rebased on the hintsforward branch.
I insist though that you should use the stdlib [`partition`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html#VALpartition) instead of your own ill-named `split_with`.

**Comment by mattam82** [comment]
Indeed you're right about partition.

**Comment by Zimmi48** [comment]
Is it planned to merge the `hintsforward` branch in 8.6beta2? I really hope so.

**Comment by mattam82** [comment]
No, it's too late.

**Comment by mattam82** [comment]
I just pushed a new hintsfoward without the split_with

**Comment by Zimmi48** [comment]
This is not relevant anymore since the fix has been integrated upstream.

**Pull request closed without merging**
